### ISSUE TITLE
Productize System.Text.Primitives

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#1090]
- [x] Fix issues in parsing APIs: #1070 
- [x] Fix issues in  formatting APIs: #1089
- [x] Fix issues in encoding APIs: #1091
- [x] Fix API review issues: #1714
- [x] Move System.Text.Primitives to corefx repo: #1716
- [ ] Design APIs to create non-invariant/custom SymbolTables
- [ ] Review the APIs with globalization experts
- [x] Write solid documentation, blog, getting started guide
- [x] Remove dependencies from System.Text.Primitives to System.Slices. The component should depend on System.Memory only.
- [x] Remove all TODOs from source code.

**Comment by KrzysztofCwalina** [comment]
@joshfree, @terrajobst, @shiftylogic, @ahsonkhan, @botaberg, I added this issue to track overall work related productizing the System.Text.Primitives component. Feel free to add/tweak workitems.

**Comment by ahsonkhan** [comment]
Should we add cleaning up some of the outdated/unnecessary benchmark tests that are part of System.Text.Primitives here so we don't have 500+?

**Comment by botaberg** [comment]
@ahsonkhan We can definitely remove some of the tests. I was thinking about removing all of the tests in InternalParserTests.tt and InternalParserPerfTests.cs. However, this will not remove any benchmarks from System.Text.Primitives since all benchmarks in InternalParserPerfTests are disabled. We may need to do something else to decrease the testing time. Doesn't most of the time come from the E2EPipelineTests? Can we split those out into a separate assembly?

**Comment by KrzysztofCwalina** [comment]
I updated the issue with workitems that have been completed. The two that are not completed are the following:
- [ ] Design APIs to create non-invariant/custom SymbolTables
- [ ] Review the APIs with globalization experts

These two are not part of our 2.1 release. I will track them separately.
