### ISSUE TITLE
Productize Utf8String

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#2165]
- [ ] #1447 Decide on Utf8String representation
- [ ] #361 All constructing utf8string literals
- [ ] https://github.com/dotnet/csharplang/issues/909 UTF8String constants
- [ ] [Pattern-based fixed statement](https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.3/pattern-based-fixed.md) for Utf8String

**Comment by joshfree** [comment]
related https://github.com/dotnet/corefx/issues/29290 - Add UTF-8 match APIs to System.IO.Enumeration
