### ISSUE TITLE
Bedrock Dependencies

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dotnet/corefxlab#2225]
Pri 1

- [ ] BufferReader/BufferWriter #2166 (@JeremyKuhne) 
- [x] JsonReader/JsonWriter #2167 (@ahsonkhan)
- [ ] Utf8String #2165 (@GrabYourPitchforks)
- [ ] HttpParser/Writer
- [ ] HTTP/2 Parser/Writer/Model

Pr 2
-  [ ] TLS flat APIs

cc: @joshfree, @davidfowl

**Comment by joshfree** [comment]
@davidfowl can you share your screenshot of the list we came up with yesterday or edit the issue inline?

fyi: @glennc

**Comment by davidfowl** [comment]
@KrzysztofCwalina took the screenshot 😄

**Comment by shaggygi** [comment]
Referencing https://github.com/aspnet/KestrelHttpServer/issues/1980
